spring:
  application:
    name: rss
  r2dbc:
    url: r2dbc:h2:mem:///localdb?options=DB_CLOSE_DELAY=-1;MODE=MariaDB;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
server:
  port: 3001